branch-defaults:
  default:
    environment: car-rental-env
global:
  application_name: car-rental-backend
  branch: null
  default_ec2_keyname: car-rental-key
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
